In [14]:
import pandas as pd
import numpy as np

from constants import numeric_columns as num_cols


train_df = pd.read_csv('dm1_dataset_2425_imdb/train.csv')
test_df = pd.read_csv('dm1_dataset_2425_imdb/test.csv')

complete_df = pd.concat([train_df, test_df], ignore_index = True)
complete_df

originalTitle  rating  startYear endYear  \
0      Neogenic Nightmare Chapter 3: Hydro-Man  (7, 8]       1995      \N   
1                                      Looping  (5, 6]       1982      \N   
2                               Idealnaya para  (5, 6]       1992      \N   
3                  MasterChef Celebrity México  (5, 6]       2021      \N   
4                                  Seutateueob  (7, 8]       2020    2020   
...                                        ...     ...        ...     ...   
21904                   Parasiz yasamak pahali  (7, 8]       1994      \N   
21905                       Wedding Bell Blues  (6, 7]       1994      \N   
21906          O anthropos pou to 'paize poly!  (3, 4]       1983      \N   
21907                   Above Average Presents  (6, 7]       2012      \N   
21908           Omae wa mada Gunma wo shiranai  (4, 5]       2017    2017   

      runtimeMinutes  awardWins  numVotes  worstRating  bestRating  \
0                 \N        0.0       779            1          10   
1                 \N        0.0        11            1          10   
2                 \N        0.0        38            1          10   
3                 \N        0.0        15            1          10   
4                 80        1.0     15718            1          10   
...              ...        ...       ...          ...         ...   
21904            141        NaN        45            1          10   
21905             22        0.0        19            1          10   
21906             85        NaN        14            1          10   
21907             \N        0.0       111            1          10   
21908             30        NaN        11            1          10   

       totalImages  ...     titleType  awardNominationsExcludeWins  \
0                1  ...     tvEpisode                            0   
1                1  ...     videoGame                            0   
2                1  ...         movie                            0   
3               22  ...      tvSeries                            0   
4              347  ...      tvSeries                            1   
...            ...  ...           ...                          ...   
21904            1  ...         video                            0   
21905           17  ...     tvEpisode                            0   
21906            1  ...         movie                            0   
21907           56  ...      tvSeries                            0   
21908            1  ...  tvMiniSeries                            0   

       canHaveEpisodes isRatable  isAdult  numRegions  userReviewsTotal  \
0                False      True        0           1                 0   
1                False      True        0           1                 0   
2                False      True        0           1                 1   
3                 True      True        0           1                 0   
4                 True      True        0          32               452   
...                ...       ...      ...         ...               ...   
21904            False      True        0           1                 0   
21905            False      True        0           1                 0   
21906            False      True        0           1                 0   
21907             True      True        0           2                 3   
21908             True      True        0           1                 0   

       ratingCount  countryOfOrigin                      genres  
0              781           ['US']  Action,Adventure,Animation  
1               11          ['XWG']                      Action  
2               38           ['RU']                      Comedy  
3               15           ['MX']                  Reality-TV  
4            15746           ['KR']        Comedy,Drama,Romance  
...            ...              ...                         ...  
21904           45           ['TR']                      Comedy

In [4]:
for col in num_cols:
    complete_df[col] = pd.to_numeric(complete_df[col], errors='coerce')
# train_df[num_cols] = pd.to_numeric(train_df[num_cols], errors='coerce')

complete_df.loc[complete_df['genres'] == r'\N', 'genres'] = np.nan
complete_df

originalTitle  rating  startYear  endYear  \
0      Neogenic Nightmare Chapter 3: Hydro-Man  (7, 8]       1995      NaN   
1                                      Looping  (5, 6]       1982      NaN   
2                               Idealnaya para  (5, 6]       1992      NaN   
3                  MasterChef Celebrity México  (5, 6]       2021      NaN   
4                                  Seutateueob  (7, 8]       2020   2020.0   
...                                        ...     ...        ...      ...   
21904                   Parasiz yasamak pahali  (7, 8]       1994      NaN   
21905                       Wedding Bell Blues  (6, 7]       1994      NaN   
21906          O anthropos pou to 'paize poly!  (3, 4]       1983      NaN   
21907                   Above Average Presents  (6, 7]       2012      NaN   
21908           Omae wa mada Gunma wo shiranai  (4, 5]       2017   2017.0   

       runtimeMinutes  awardWins  numVotes  worstRating  bestRating  \
0                 NaN        0.0       779            1          10   
1                 NaN        0.0        11            1          10   
2                 NaN        0.0        38            1          10   
3                 NaN        0.0        15            1          10   
4                80.0        1.0     15718            1          10   
...               ...        ...       ...          ...         ...   
21904           141.0        NaN        45            1          10   
21905            22.0        0.0        19            1          10   
21906            85.0        NaN        14            1          10   
21907             NaN        0.0       111            1          10   
21908            30.0        NaN        11            1          10   

       totalImages  ...     titleType  awardNominationsExcludeWins  \
0                1  ...     tvEpisode                            0   
1                1  ...     videoGame                            0   
2                1  ...         movie                            0   
3               22  ...      tvSeries                            0   
4              347  ...      tvSeries                            1   
...            ...  ...           ...                          ...   
21904            1  ...         video                            0   
21905           17  ...     tvEpisode                            0   
21906            1  ...         movie                            0   
21907           56  ...      tvSeries                            0   
21908            1  ...  tvMiniSeries                            0   

       canHaveEpisodes isRatable  isAdult  numRegions  userReviewsTotal  \
0                False      True        0           1                 0   
1                False      True        0           1                 0   
2                False      True        0           1                 1   
3                 True      True        0           1                 0   
4                 True      True        0          32               452   
...                ...       ...      ...         ...               ...   
21904            False      True        0           1                 0   
21905            False      True        0           1                 0   
21906            False      True        0           1                 0   
21907             True      True        0           2                 3   
21908             True      True        0           1                 0   

       ratingCount  countryOfOrigin                      genres  
0              781           ['US']  Action,Adventure,Animation  
1               11          ['XWG']                      Action  
2               38           ['RU']                      Comedy  
3               15           ['MX']                  Reality-TV  
4            15746           ['KR']        Comedy,Drama,Romance  
...            ...              ...                         ...  
21904           45           ['TR']    

In [15]:
complete_df['rating'].unique()

array(['(7, 8]', '(5, 6]', '(8, 9]', '(6, 7]', '(2, 3]', '(4, 5]',
       '(9, 10]', '(3, 4]', '(0, 1]', '(1, 2]'], dtype=object)

In [16]:
# swaps the rating column to contain only the integer values of the higher bounds
complete_df['rating'] = complete_df['rating'].str.extract(
        r",\s*(\d+)\]"
    ).astype(int)

complete_df

originalTitle  rating  startYear endYear  \
0      Neogenic Nightmare Chapter 3: Hydro-Man       8       1995      \N   
1                                      Looping       6       1982      \N   
2                               Idealnaya para       6       1992      \N   
3                  MasterChef Celebrity México       6       2021      \N   
4                                  Seutateueob       8       2020    2020   
...                                        ...     ...        ...     ...   
21904                   Parasiz yasamak pahali       8       1994      \N   
21905                       Wedding Bell Blues       7       1994      \N   
21906          O anthropos pou to 'paize poly!       4       1983      \N   
21907                   Above Average Presents       7       2012      \N   
21908           Omae wa mada Gunma wo shiranai       5       2017    2017   

      runtimeMinutes  awardWins  numVotes  worstRating  bestRating  \
0                 \N        0.0       779            1          10   
1                 \N        0.0        11            1          10   
2                 \N        0.0        38            1          10   
3                 \N        0.0        15            1          10   
4                 80        1.0     15718            1          10   
...              ...        ...       ...          ...         ...   
21904            141        NaN        45            1          10   
21905             22        0.0        19            1          10   
21906             85        NaN        14            1          10   
21907             \N        0.0       111            1          10   
21908             30        NaN        11            1          10   

       totalImages  ...     titleType  awardNominationsExcludeWins  \
0                1  ...     tvEpisode                            0   
1                1  ...     videoGame                            0   
2                1  ...         movie                            0   
3               22  ...      tvSeries                            0   
4              347  ...      tvSeries                            1   
...            ...  ...           ...                          ...   
21904            1  ...         video                            0   
21905           17  ...     tvEpisode                            0   
21906            1  ...         movie                            0   
21907           56  ...      tvSeries                            0   
21908            1  ...  tvMiniSeries                            0   

       canHaveEpisodes isRatable  isAdult  numRegions  userReviewsTotal  \
0                False      True        0           1                 0   
1                False      True        0           1                 0   
2                False      True        0           1                 1   
3                 True      True        0           1                 0   
4                 True      True        0          32               452   
...                ...       ...      ...         ...               ...   
21904            False      True        0           1                 0   
21905            False      True        0           1                 0   
21906            False      True        0           1                 0   
21907             True      True        0           2                 3   
21908             True      True        0           1                 0   

       ratingCount  countryOfOrigin                      genres  
0              781           ['US']  Action,Adventure,Animation  
1               11          ['XWG']                      Action  
2               38           ['RU']                      Comedy  
3               15           ['MX']                  Reality-TV  
4            15746           ['KR']        Comedy,Drama,Romance  
...            ...              ...                         ...  
21904           45           ['TR']                      Comedy

In [17]:
complete_df['rating'].unique()

array([ 8,  6,  9,  7,  3,  5, 10,  4,  1,  2])

In [20]:
complete_df['worstRating'].unique()

array([1])

In [21]:
complete_df['bestRating'].unique()

array([10])

In [22]:
complete_df['startYear'].unique()

array([1995, 1982, 1992, 2021, 2020, 2022, 1996, 2017, 1980, 1965, 2014,
       2004, 2009, 2023, 1984, 2016, 1900, 1997, 1970, 1943, 1968, 2007,
       1961, 1959, 1999, 1986, 1958, 1966, 1993, 2012, 1976, 1989, 2018,
       2003, 2008, 1932, 1906, 1898, 1914, 1975, 1960, 2015, 1953, 2010,
       1941, 1981, 2013, 1987, 1998, 1988, 2011, 2006, 1901, 2002, 1977,
       1915, 1974, 1979, 1991, 1964, 1983, 1985, 2005, 1934, 1951, 1994,
       1971, 1919, 2019, 1963, 1926, 1903, 1936, 1957, 1990, 2024, 1952,
       1911, 1950, 1947, 1972, 1955, 1978, 1949, 1969, 1935, 1929, 1946,
       1939, 1909, 1918, 1927, 1962, 1967, 1973, 2001, 1912, 1942, 1945,
       1928, 1948, 1944, 1931, 1938, 1894, 1899, 1908, 1937, 1896, 1956,
       1913, 1922, 1954, 1933, 1925, 1897, 1930, 1924, 1940, 1921, 1917,
       1916, 1923, 1920, 1910, 1905, 1907, 1902, 1895, 1904, 1893, 1891,
       1878])

In [23]:
complete_df['endYear'].unique()

array(['\\N', '2020', '1999', '2016', '2009', '2023', '2015', '1984',
       '2022', '2007', '1997', '2014', '2024', '2019', '2004', '2021',
       '2017', '1995', '1986', '1977', '1979', '1953', '1998', '1973',
       '1989', '1961', '1994', '2002', '2018', '1991', '2012', '2000',
       '2006', '1975', '1996', '1969', '1990', '1955', '1970', '1980',
       '1985', '1968', '2011', '1993', '1959', '1971', '1988', '2013',
       '1966', '1960', '1981', '1983', '1972', '1987', '1952', '1967',
       '2010', '2005', '1951', '1963', '1978', '2001', '2008', '1982',
       '1974', '2003', '1976', '1954', '1992', '1956', '1945', '1958',
       '2025', '1962', '1957', '1965'], dtype=object)

In [ ]:
complete_df.groupby('endYear').count()['rating']

endYear
1945        1
1951        1
1952        3
1953        3
1954        1
        ...  
2022       48
2023       41
2024       18
2025        1
\N      20822
Name: originalTitle, Length: 76, dtype: int64

In [ ]:
complete_df.groupby('genres').count()['rating']

genres
Action                    163
Action,Adult                3
Action,Adult,Adventure      1
Action,Adult,Animation      1
Action,Adult,Comedy         2
                         ... 
Thriller                  153
Thriller,War                2
War                        16
Western                   244
\N                        503
Name: titleType, Length: 858, dtype: int64

In [ ]:
# THIS SHOWS THAT ROWS WITH NO EPISODES DO NOT HAVE ENDYEAR
complete_df.groupby(['canHaveEpisodes', 'endYear']).count()['rating']

canHaveEpisodes  endYear
False            \N         19782
True             1945           1
                 1951           1
                 1952           3
                 1953           3
                            ...  
                 2022          48
                 2023          41
                 2024          18
                 2025           1
                 \N          1040
Name: originalTitle, Length: 77, dtype: int64

In [ ]:
# half of the rows with canHaveEpisodes = True do not have an endYear
complete_df.groupby('canHaveEpisodes').count()['rating']

canHaveEpisodes
False    19782
True      2127
Name: originalTitle, dtype: int64

In [36]:
complete_df.loc[complete_df['canHaveEpisodes']].groupby(
        ['canHaveEpisodes', 'endYear', 'startYear']
    ).count()['rating']

canHaveEpisodes  endYear  startYear
True             1945     1940          1
                 1951     1950          1
                 1952     1948          1
                          1951          2
                 1953     1951          1
                                       ..
                 \N       2020         32
                          2021         55
                          2022         42
                          2023         42
                          2024         16
Name: rating, Length: 466, dtype: int64

In [38]:
# all true lol
complete_df.groupby('isRatable').count()['rating']

isRatable
True    21909
Name: rating, dtype: int64

In [39]:
complete_df['runtimeMinutes'].unique()

array(['\\N', '80', '34', '45', '12', '44', '60', '90', '82', '21', '122',
       '17', '1', '30', '23', '93', '57', '74', '85', '83', '75', '78',
       '28', '184', '25', '10', '108', '40', '98', '110', '48', '50',
       '89', '42', '71', '79', '4', '43', '41', '6', '101', '77', '14',
       '16', '7', '24', '3', '105', '20', '8', '49', '29', '26', '22',
       '143', '11', '47', '97', '46', '65', '94', '62', '51', '100', '27',
       '35', '95', '103', '72', '18', '69', '39', '87', '99', '59', '64',
       '96', '68', '15', '185', '67', '126', '86', '118', '104', '114',
       '91', '88', '106', '137', '66', '240', '117', '70', '32', '120',
       '115', '142', '73', '58', '111', '9', '134', '128', '13', '52',
       '102', '55', '76', '109', '139', '107', '528', '2', '53', '92',
       '31', '166', '19', '5', '56', '180', '146', '132', '220', '81',
       '173', '300', '54', '123', '168', '84', '36', '155', '153', '119',
       '63', '178', '130', '149', '175', '165', '600', '113'

In [42]:
complete_df.groupby('runtimeMinutes').count()['rating']

runtimeMinutes
0         1
1       107
10      196
100     203
101      83
       ... 
96      138
97      133
98      128
99       76
\N     6512
Name: rating, Length: 255, dtype: int64

In [49]:
complete_df.groupby(['canHaveEpisodes', 'runtimeMinutes']).count()['rating']

canHaveEpisodes  runtimeMinutes
False            0                    1
                 1                  101
                 10                 189
                 100                199
                 101                 83
                                   ... 
True             89                   1
                 9                    1
                 90                  15
                 96                   1
                 \N                1061
Name: rating, Length: 360, dtype: int64

In [ ]:
complete_df.loc[complete_df['']].groupby()

In [18]:
complete_df.columns

Index(['originalTitle', 'rating', 'startYear', 'endYear', 'runtimeMinutes',
       'awardWins', 'numVotes', 'worstRating', 'bestRating', 'totalImages',
       'totalVideos', 'totalCredits', 'criticReviewsTotal', 'titleType',
       'awardNominationsExcludeWins', 'canHaveEpisodes', 'isRatable',
       'isAdult', 'numRegions', 'userReviewsTotal', 'ratingCount',
       'countryOfOrigin', 'genres'],
      dtype='object')